// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: plugin/github.com.openbao.go.kms.wrapping.plugin.v2.proto

package plugin

import (
	v2 "github.com/openbao/go-kms-wrapping/v2"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeRequest) Reset() {
	*x = TypeRequest{}
	mi := &file_plugin_github_com_openbao_go_kms_wrapping_plugin_v2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeRequest) ProtoMessage() {}

func (x *TypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_github_com_openbao_go_kms_wrapping_plugin_v2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeRequest.ProtoReflect.Descriptor instead.
func (*TypeRequest) Descriptor() ([]byte, []int) {
	return file_plugin_github_com_openbao_go_kms_wrapping_plugin_v2_proto_rawDescGZIP(), []int{0}
}

type TypeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,10,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeResponse) Reset() {
	*x = TypeResponse{}
	mi := &file_plugin_github_com_openbao_go_kms_wrapping_plugin_v2_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeResponse) ProtoMessage() {}

func (x *TypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_github_com_openbao_go_kms_wrapping_plugin_v2_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeResponse.ProtoReflect.Descriptor instead.
func (*TypeResponse) Descriptor() ([]byte, []int) {
	return file_plugin_github_com_openbao_go_kms_wrapping_plugin_v2_proto_rawDescGZIP(), []int{1}
}

func (x *TypeResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type KeyIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyIdRequest) Reset() {
	*x = KeyIdRequest{}
	mi := &file_plugin_github_com_openbao_go_kms_wrapping_plugin_v2_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyIdRequest) ProtoMessage() {}

func (x *KeyIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_github_com_openbao_go_kms_wrapping_plugin_v2_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyIdRequest.ProtoReflect.Descriptor instead.
func (*KeyIdRequest) Descriptor() ([]byte, []int) {
	return file_plugin_github_com_openbao_go_kms_wrapping_plugin_v2_proto_rawDescGZIP(), []int{2}
}

type KeyIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,10,opt,name=key_id,proto3" json:"key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyIdResponse) Reset() {
	*x = KeyIdResponse{}
	mi := &file_plugin_github_com_openbao_go_kms_wrapping_plugin_v2_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyIdResponse) ProtoMessage() {}

func (x *KeyIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_github_com_openbao_go_kms_wrapping_plugin_v2_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyIdResponse.ProtoReflect.Descriptor instead.
func (*KeyIdResponse) Descriptor() ([]byte, []int) {
	return file_plugin_github_com_openbao_go_kms_wrapping_plugin_v2_proto_rawDescGZIP(), []int{3}
}

func (x *KeyIdResponse) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

type SetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Options       *v2.Options            `protobuf:"bytes,20,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetConfigRequest) Reset() {
	*x = SetConfigRequest{}
	mi := &file_plugin_github_com_openbao_go_kms_wrapping_plugin_v2_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConfigRequest) ProtoMessage() {}

func (x *SetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_github_com_openbao_go_kms_wrapping_plugin_v2_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetConfigRequest.ProtoReflect.Descriptor instead.
func (*SetConfigRequest) Descriptor() ([]byte, []int) {
	return file_plugin_github_com_openbao_go_kms_wrapping_plugin_v2_proto_rawDescGZIP(), []int{4}
}

func (x *SetConfigRequest) GetOptions() *v2.Options {
	if x != nil {
		return x.Options
	}
	return nil
}

type SetConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WrapperConfig *v2.WrapperConfig      `protobuf:"bytes,10,opt,name=wrapper_config,json=wrapperConfig,proto3" json:"wrapper_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetConfigResponse) Reset() {
	*x = SetConfigResponse{}
	mi := &file_plugin_github_com_openbao_go_kms_wrapping_plugin_v2_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConfigResponse) ProtoMessage() {}

func (x *SetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_github_com_openbao_go_kms_wrapping_plugin_v2_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetConfigResponse.ProtoReflect.Descriptor instead.
func (*SetConfigResponse) Descriptor() ([]byte, []int) {
	return file_plugin_github_com_openbao_go_kms_wrapping_plugin_v2_proto_rawDescGZIP(), []int{5}
}

func (x *SetConfigResponse) GetWrapperConfig() *v2.WrapperConfig {
	if x != nil {
		return x.WrapperConfig
	}
	return nil
}

type EncryptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plaintext     []byte                 `protobuf:"bytes,10,opt,name=plaintext,proto3" json:"plaintext,omitempty"`
	Options       *v2.Options            `protobuf:"bytes,20,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncryptRequest) Reset() {
	*x = EncryptRequest{}
	mi := &file_plugin_github_com_openbao_go_kms_wrapping_plugin_v2_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptRequest) ProtoMessage() {}

func (x *EncryptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_github_com_openbao_go_kms_wrapping_plugin_v2_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptRequest.ProtoReflect.Descriptor instead.
func (*EncryptRequest) Descriptor() ([]byte, []int) {
	return file_plugin_github_com_openbao_go_kms_wrapping_plugin_v2_proto_rawDescGZIP(), []int{6}
}

func (x *EncryptRequest) GetPlaintext() []byte {
	if x != nil {
		return x.Plaintext
	}
	return nil
}

func (x *EncryptRequest) GetOptions() *v2.Options {
	if x != nil {
		return x.Options
	}
	return nil
}

type EncryptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ciphertext    *v2.BlobInfo           `protobuf:"bytes,10,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncryptResponse) Reset() {
	*x = EncryptResponse{}
	mi := &file_plugin_github_com_openbao_go_kms_wrapping_plugin_v2_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptResponse) ProtoMessage() {}

func (x *EncryptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_github_com_openbao_go_kms_wrapping_plugin_v2_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptResponse.ProtoReflect.Descriptor instead.
func (*EncryptResponse) Descriptor() ([]byte, []int) {
	return file_plugin_github_com_openbao_go_kms_wrapping_plugin_v2_proto_rawDescGZIP(), []int{7}
}

func (x *EncryptResponse) GetCiphertext() *v2.BlobInfo {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

type DecryptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ciphertext    *v2.BlobInfo           `protobuf:"bytes,10,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	Options       *v2.Options            `protobuf:"bytes,20,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecryptRequest) Reset() {
	*x = DecryptRequest{}
	mi := &file_plugin_github_com_openbao_go_kms_wrapping_plugin_v2_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecryptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecryptRequest) ProtoMessage() {}

func (x *DecryptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_github_com_openbao_go_kms_wrapping_plugin_v2_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecryptRequest.ProtoReflect.Descriptor instead.
func (*DecryptRequest) Descriptor() ([]byte, []int) {
	return file_plugin_github_com_openbao_go_kms_wrapping_plugin_v2_proto_rawDescGZIP(), []int{8}
}

func (x *DecryptRequest) GetCiphertext() *v2.BlobInfo {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

func (x *DecryptRequest) GetOptions() *v2.Options {
	if x != nil {
		return x.Options
	}
	return nil
}

type DecryptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plaintext     []byte                 `protobuf:"bytes,10,opt,name=plaintext,proto3" json:"plaintext,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecryptResponse) Reset() {
	*x = DecryptResponse{}
	mi := &file_plugin_github_com_openbao_go_kms_wrapping_plugin_v2_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecryptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecryptResponse) ProtoMessage() {}

func (x *DecryptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_github_com_openbao_go_kms_wrapping_plugin_v2_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecryptResponse.ProtoReflect.Descriptor instead.
func (*DecryptResponse) Descriptor() ([]byte, []int) {
	return file_plugin_github_com_openbao_go_kms_wrapping_plugin_v2_proto_rawDescGZIP(), []int{9}
}

func (x *DecryptResponse) GetPlaintext() []byte {
	if x != nil {
		return x.Plaintext
	}
	return nil
}

type InitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Options       *v2.Options            `protobuf:"bytes,20,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitRequest) Reset() {
	*x = InitRequest{}
	mi := &file_plugin_github_com_openbao_go_kms_wrapping_plugin_v2_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequest) ProtoMessage() {}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_github_com_openbao_go_kms_wrapping_plugin_v2_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequest.ProtoReflect.Descriptor instead.
func (*InitRequest) Descriptor() ([]byte, []int) {
	return file_plugin_github_com_openbao_go_kms_wrapping_plugin_v2_proto_rawDescGZIP(), []int{10}
}

func (x *InitRequest) GetOptions() *v2.Options {
	if x != nil {
		return x.Options
	}
	return nil
}

type InitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitResponse) Reset() {
	*x = InitResponse{}
	mi := &file_plugin_github_com_openbao_go_kms_wrapping_plugin_v2_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitResponse) ProtoMessage() {}

func (x *InitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_github_com_openbao_go_kms_wrapping_plugin_v2_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitResponse.ProtoReflect.Descriptor instead.
func (*InitResponse) Descriptor() ([]byte, []int) {
	return file_plugin_github_com_openbao_go_kms_wrapping_plugin_v2_proto_rawDescGZIP(), []int{11}
}

type FinalizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Options       *v2.Options            `protobuf:"bytes,20,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizeRequest) Reset() {
	*x = FinalizeRequest{}
	mi := &file_plugin_github_com_openbao_go_kms_wrapping_plugin_v2_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeRequest) ProtoMessage() {}

func (x *FinalizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_github_com_openbao_go_kms_wrapping_plugin_v2_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeRequest.ProtoReflect.Descriptor instead.
func (*FinalizeRequest) Descriptor() ([]byte, []int) {
	return file_plugin_github_com_openbao_go_kms_wrapping_plugin_v2_proto_rawDescGZIP(), []int{12}
}

func (x *FinalizeRequest) GetOptions() *v2.Options {
	if x != nil {
		return x.Options
	}
	return nil
}

type FinalizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizeResponse) Reset() {
	*x = FinalizeResponse{}
	mi := &file_plugin_github_com_openbao_go_kms_wrapping_plugin_v2_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeResponse) ProtoMessage() {}

func (x *FinalizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_github_com_openbao_go_kms_wrapping_plugin_v2_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeResponse.ProtoReflect.Descriptor instead.
func (*FinalizeResponse) Descriptor() ([]byte, []int) {
	return file_plugin_github_com_openbao_go_kms_wrapping_plugin_v2_proto_rawDescGZIP(), []int{13}
}

type KeyBytesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyBytesRequest) Reset() {
	*x = KeyBytesRequest{}
	mi := &file_plugin_github_com_openbao_go_kms_wrapping_plugin_v2_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyBytesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyBytesRequest) ProtoMessage() {}

func (x *KeyBytesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_github_com_openbao_go_kms_wrapping_plugin_v2_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyBytesRequest.ProtoReflect.Descriptor instead.
func (*KeyBytesRequest) Descriptor() ([]byte, []int) {
	return file_plugin_github_com_openbao_go_kms_wrapping_plugin_v2_proto_rawDescGZIP(), []int{14}
}

type KeyBytesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyBytes      []byte                 `protobuf:"bytes,10,opt,name=key_bytes,proto3" json:"key_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyBytesResponse) Reset() {
	*x = KeyBytesResponse{}
	mi := &file_plugin_github_com_openbao_go_kms_wrapping_plugin_v2_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyBytesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyBytesResponse) ProtoMessage() {}

func (x *KeyBytesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_github_com_openbao_go_kms_wrapping_plugin_v2_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyBytesResponse.ProtoReflect.Descriptor instead.
func (*KeyBytesResponse) Descriptor() ([]byte, []int) {
	return file_plugin_github_com_openbao_go_kms_wrapping_plugin_v2_proto_rawDescGZIP(), []int{15}
}

func (x *KeyBytesResponse) GetKeyBytes() []byte {
	if x != nil {
		return x.KeyBytes
	}
	return nil
}

var File_plugin_github_com_openbao_go_kms_wrapping_plugin_v2_proto protoreflect.FileDescriptor

const file_plugin_github_com_openbao_go_kms_wrapping_plugin_v2_proto_rawDesc = "" +
	"\n" +
	"9plugin/github.com.openbao.go.kms.wrapping.plugin.v2.proto\x12,github.com.openbao.go.kms.wrapping.plugin.v2\x1a1github.com.openbao.go.kms.wrapping.v2.types.proto\"\r\n" +
	"\vTypeRequest\"\"\n" +
	"\fTypeResponse\x12\x12\n" +
	"\x04type\x18\n" +
	" \x01(\tR\x04type\"\x0e\n" +
	"\fKeyIdRequest\"'\n" +
	"\rKeyIdResponse\x12\x16\n" +
	"\x06key_id\x18\n" +
	" \x01(\tR\x06key_id\"b\n" +
	"\x10SetConfigRequest\x12N\n" +
	"\aoptions\x18\x14 \x01(\v24.github.com.openbao.go.kms.wrapping.v2.types.OptionsR\aoptions\"v\n" +
	"\x11SetConfigResponse\x12a\n" +
	"\x0ewrapper_config\x18\n" +
	" \x01(\v2:.github.com.openbao.go.kms.wrapping.v2.types.WrapperConfigR\rwrapperConfig\"~\n" +
	"\x0eEncryptRequest\x12\x1c\n" +
	"\tplaintext\x18\n" +
	" \x01(\fR\tplaintext\x12N\n" +
	"\aoptions\x18\x14 \x01(\v24.github.com.openbao.go.kms.wrapping.v2.types.OptionsR\aoptions\"h\n" +
	"\x0fEncryptResponse\x12U\n" +
	"\n" +
	"ciphertext\x18\n" +
	" \x01(\v25.github.com.openbao.go.kms.wrapping.v2.types.BlobInfoR\n" +
	"ciphertext\"\xb7\x01\n" +
	"\x0eDecryptRequest\x12U\n" +
	"\n" +
	"ciphertext\x18\n" +
	" \x01(\v25.github.com.openbao.go.kms.wrapping.v2.types.BlobInfoR\n" +
	"ciphertext\x12N\n" +
	"\aoptions\x18\x14 \x01(\v24.github.com.openbao.go.kms.wrapping.v2.types.OptionsR\aoptions\"/\n" +
	"\x0fDecryptResponse\x12\x1c\n" +
	"\tplaintext\x18\n" +
	" \x01(\fR\tplaintext\"]\n" +
	"\vInitRequest\x12N\n" +
	"\aoptions\x18\x14 \x01(\v24.github.com.openbao.go.kms.wrapping.v2.types.OptionsR\aoptions\"\x0e\n" +
	"\fInitResponse\"a\n" +
	"\x0fFinalizeRequest\x12N\n" +
	"\aoptions\x18\x14 \x01(\v24.github.com.openbao.go.kms.wrapping.v2.types.OptionsR\aoptions\"\x12\n" +
	"\x10FinalizeResponse\"\x11\n" +
	"\x0fKeyBytesRequest\"0\n" +
	"\x10KeyBytesResponse\x12\x1c\n" +
	"\tkey_bytes\x18\n" +
	" \x01(\fR\tkey_bytes2\xc3\b\n" +
	"\aWrapper\x12}\n" +
	"\x04Type\x129.github.com.openbao.go.kms.wrapping.plugin.v2.TypeRequest\x1a:.github.com.openbao.go.kms.wrapping.plugin.v2.TypeResponse\x12\x80\x01\n" +
	"\x05KeyId\x12:.github.com.openbao.go.kms.wrapping.plugin.v2.KeyIdRequest\x1a;.github.com.openbao.go.kms.wrapping.plugin.v2.KeyIdResponse\x12\x8c\x01\n" +
	"\tSetConfig\x12>.github.com.openbao.go.kms.wrapping.plugin.v2.SetConfigRequest\x1a?.github.com.openbao.go.kms.wrapping.plugin.v2.SetConfigResponse\x12\x86\x01\n" +
	"\aEncrypt\x12<.github.com.openbao.go.kms.wrapping.plugin.v2.EncryptRequest\x1a=.github.com.openbao.go.kms.wrapping.plugin.v2.EncryptResponse\x12\x86\x01\n" +
	"\aDecrypt\x12<.github.com.openbao.go.kms.wrapping.plugin.v2.DecryptRequest\x1a=.github.com.openbao.go.kms.wrapping.plugin.v2.DecryptResponse\x12}\n" +
	"\x04Init\x129.github.com.openbao.go.kms.wrapping.plugin.v2.InitRequest\x1a:.github.com.openbao.go.kms.wrapping.plugin.v2.InitResponse\x12\x89\x01\n" +
	"\bFinalize\x12=.github.com.openbao.go.kms.wrapping.plugin.v2.FinalizeRequest\x1a>.github.com.openbao.go.kms.wrapping.plugin.v2.FinalizeResponse\x12\x89\x01\n" +
	"\bKeyBytes\x12=.github.com.openbao.go.kms.wrapping.plugin.v2.KeyBytesRequest\x1a>.github.com.openbao.go.kms.wrapping.plugin.v2.KeyBytesResponseB5Z3github.com/openbao/go-kms-wrapping/v2/plugin;pluginb\x06proto3"

var (
	file_plugin_github_com_openbao_go_kms_wrapping_plugin_v2_proto_rawDescOnce sync.Once
	file_plugin_github_com_openbao_go_kms_wrapping_plugin_v2_proto_rawDescData []byte
)

func file_plugin_github_com_openbao_go_kms_wrapping_plugin_v2_proto_rawDescGZIP() []byte {
	file_plugin_github_com_openbao_go_kms_wrapping_plugin_v2_proto_rawDescOnce.Do(func() {
		file_plugin_github_com_openbao_go_kms_wrapping_plugin_v2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_github_com_openbao_go_kms_wrapping_plugin_v2_proto_rawDesc), len(file_plugin_github_com_openbao_go_kms_wrapping_plugin_v2_proto_rawDesc)))
	})
	return file_plugin_github_com_openbao_go_kms_wrapping_plugin_v2_proto_rawDescData
}

var file_plugin_github_com_openbao_go_kms_wrapping_plugin_v2_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_plugin_github_com_openbao_go_kms_wrapping_plugin_v2_proto_goTypes = []any{
	(*TypeRequest)(nil),       // 0: github.com.openbao.go.kms.wrapping.plugin.v2.TypeRequest
	(*TypeResponse)(nil),      // 1: github.com.openbao.go.kms.wrapping.plugin.v2.TypeResponse
	(*KeyIdRequest)(nil),      // 2: github.com.openbao.go.kms.wrapping.plugin.v2.KeyIdRequest
	(*KeyIdResponse)(nil),     // 3: github.com.openbao.go.kms.wrapping.plugin.v2.KeyIdResponse
	(*SetConfigRequest)(nil),  // 4: github.com.openbao.go.kms.wrapping.plugin.v2.SetConfigRequest
	(*SetConfigResponse)(nil), // 5: github.com.openbao.go.kms.wrapping.plugin.v2.SetConfigResponse
	(*EncryptRequest)(nil),    // 6: github.com.openbao.go.kms.wrapping.plugin.v2.EncryptRequest
	(*EncryptResponse)(nil),   // 7: github.com.openbao.go.kms.wrapping.plugin.v2.EncryptResponse
	(*DecryptRequest)(nil),    // 8: github.com.openbao.go.kms.wrapping.plugin.v2.DecryptRequest
	(*DecryptResponse)(nil),   // 9: github.com.openbao.go.kms.wrapping.plugin.v2.DecryptResponse
	(*InitRequest)(nil),       // 10: github.com.openbao.go.kms.wrapping.plugin.v2.InitRequest
	(*InitResponse)(nil),      // 11: github.com.openbao.go.kms.wrapping.plugin.v2.InitResponse
	(*FinalizeRequest)(nil),   // 12: github.com.openbao.go.kms.wrapping.plugin.v2.FinalizeRequest
	(*FinalizeResponse)(nil),  // 13: github.com.openbao.go.kms.wrapping.plugin.v2.FinalizeResponse
	(*KeyBytesRequest)(nil),   // 14: github.com.openbao.go.kms.wrapping.plugin.v2.KeyBytesRequest
	(*KeyBytesResponse)(nil),  // 15: github.com.openbao.go.kms.wrapping.plugin.v2.KeyBytesResponse
	(*v2.Options)(nil),        // 16: github.com.openbao.go.kms.wrapping.v2.types.Options
	(*v2.WrapperConfig)(nil),  // 17: github.com.openbao.go.kms.wrapping.v2.types.WrapperConfig
	(*v2.BlobInfo)(nil),       // 18: github.com.openbao.go.kms.wrapping.v2.types.BlobInfo
}
var file_plugin_github_com_openbao_go_kms_wrapping_plugin_v2_proto_depIdxs = []int32{
	16, // 0: github.com.openbao.go.kms.wrapping.plugin.v2.SetConfigRequest.options:type_name -> github.com.openbao.go.kms.wrapping.v2.types.Options
	17, // 1: github.com.openbao.go.kms.wrapping.plugin.v2.SetConfigResponse.wrapper_config:type_name -> github.com.openbao.go.kms.wrapping.v2.types.WrapperConfig
	16, // 2: github.com.openbao.go.kms.wrapping.plugin.v2.EncryptRequest.options:type_name -> github.com.openbao.go.kms.wrapping.v2.types.Options
	18, // 3: github.com.openbao.go.kms.wrapping.plugin.v2.EncryptResponse.ciphertext:type_name -> github.com.openbao.go.kms.wrapping.v2.types.BlobInfo
	18, // 4: github.com.openbao.go.kms.wrapping.plugin.v2.DecryptRequest.ciphertext:type_name -> github.com.openbao.go.kms.wrapping.v2.types.BlobInfo
	16, // 5: github.com.openbao.go.kms.wrapping.plugin.v2.DecryptRequest.options:type_name -> github.com.openbao.go.kms.wrapping.v2.types.Options
	16, // 6: github.com.openbao.go.kms.wrapping.plugin.v2.InitRequest.options:type_name -> github.com.openbao.go.kms.wrapping.v2.types.Options
	16, // 7: github.com.openbao.go.kms.wrapping.plugin.v2.FinalizeRequest.options:type_name -> github.com.openbao.go.kms.wrapping.v2.types.Options
	0,  // 8: github.com.openbao.go.kms.wrapping.plugin.v2.Wrapper.Type:input_type -> github.com.openbao.go.kms.wrapping.plugin.v2.TypeRequest
	2,  // 9: github.com.openbao.go.kms.wrapping.plugin.v2.Wrapper.KeyId:input_type -> github.com.openbao.go.kms.wrapping.plugin.v2.KeyIdRequest
	4,  // 10: github.com.openbao.go.kms.wrapping.plugin.v2.Wrapper.SetConfig:input_type -> github.com.openbao.go.kms.wrapping.plugin.v2.SetConfigRequest
	6,  // 11: github.com.openbao.go.kms.wrapping.plugin.v2.Wrapper.Encrypt:input_type -> github.com.openbao.go.kms.wrapping.plugin.v2.EncryptRequest
	8,  // 12: github.com.openbao.go.kms.wrapping.plugin.v2.Wrapper.Decrypt:input_type -> github.com.openbao.go.kms.wrapping.plugin.v2.DecryptRequest
	10, // 13: github.com.openbao.go.kms.wrapping.plugin.v2.Wrapper.Init:input_type -> github.com.openbao.go.kms.wrapping.plugin.v2.InitRequest
	12, // 14: github.com.openbao.go.kms.wrapping.plugin.v2.Wrapper.Finalize:input_type -> github.com.openbao.go.kms.wrapping.plugin.v2.FinalizeRequest
	14, // 15: github.com.openbao.go.kms.wrapping.plugin.v2.Wrapper.KeyBytes:input_type -> github.com.openbao.go.kms.wrapping.plugin.v2.KeyBytesRequest
	1,  // 16: github.com.openbao.go.kms.wrapping.plugin.v2.Wrapper.Type:output_type -> github.com.openbao.go.kms.wrapping.plugin.v2.TypeResponse
	3,  // 17: github.com.openbao.go.kms.wrapping.plugin.v2.Wrapper.KeyId:output_type -> github.com.openbao.go.kms.wrapping.plugin.v2.KeyIdResponse
	5,  // 18: github.com.openbao.go.kms.wrapping.plugin.v2.Wrapper.SetConfig:output_type -> github.com.openbao.go.kms.wrapping.plugin.v2.SetConfigResponse
	7,  // 19: github.com.openbao.go.kms.wrapping.plugin.v2.Wrapper.Encrypt:output_type -> github.com.openbao.go.kms.wrapping.plugin.v2.EncryptResponse
	9,  // 20: github.com.openbao.go.kms.wrapping.plugin.v2.Wrapper.Decrypt:output_type -> github.com.openbao.go.kms.wrapping.plugin.v2.DecryptResponse
	11, // 21: github.com.openbao.go.kms.wrapping.plugin.v2.Wrapper.Init:output_type -> github.com.openbao.go.kms.wrapping.plugin.v2.InitResponse
	13, // 22: github.com.openbao.go.kms.wrapping.plugin.v2.Wrapper.Finalize:output_type -> github.com.openbao.go.kms.wrapping.plugin.v2.FinalizeResponse
	15, // 23: github.com.openbao.go.kms.wrapping.plugin.v2.Wrapper.KeyBytes:output_type -> github.com.openbao.go.kms.wrapping.plugin.v2.KeyBytesResponse
	16, // [16:24] is the sub-list for method output_type
	8,  // [8:16] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_plugin_github_com_openbao_go_kms_wrapping_plugin_v2_proto_init() }
func file_plugin_github_com_openbao_go_kms_wrapping_plugin_v2_proto_init() {
	if File_plugin_github_com_openbao_go_kms_wrapping_plugin_v2_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_github_com_openbao_go_kms_wrapping_plugin_v2_proto_rawDesc), len(file_plugin_github_com_openbao_go_kms_wrapping_plugin_v2_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_github_com_openbao_go_kms_wrapping_plugin_v2_proto_goTypes,
		DependencyIndexes: file_plugin_github_com_openbao_go_kms_wrapping_plugin_v2_proto_depIdxs,
		MessageInfos:      file_plugin_github_com_openbao_go_kms_wrapping_plugin_v2_proto_msgTypes,
	}.Build()
	File_plugin_github_com_openbao_go_kms_wrapping_plugin_v2_proto = out.File
	file_plugin_github_com_openbao_go_kms_wrapping_plugin_v2_proto_goTypes = nil
	file_plugin_github_com_openbao_go_kms_wrapping_plugin_v2_proto_depIdxs = nil
}
