name: Setup integration test

inputs:
  module:
    description: Module path relative to the repository root to set up at, e.g. wrappers/ovhkms
    required: true

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        ref: ${{ github.event.pull_request.head.sha || github.sha }}
        allow-unsafe-pr-checkout: true
        persist-credentials: false

    - name: Set up Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        go-version-file: ${{ inputs.module }}/go.mod
        cache-dependency-path: ${{ inputs.module }}/go.mod
