name: Go

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        directory:
          - '.'
          - './entropy'
          - './plugin'
          - './wrappers/aead'
          - './wrappers/alicloudkms'
          - './wrappers/awskms'
          - './wrappers/azurekeyvault'
          - './wrappers/gcpckms'
          - './wrappers/huaweicloudkms'
          - './wrappers/kmip'
          - './wrappers/ocikms'
          - './wrappers/pkcs11'
          - './wrappers/static'
          - './wrappers/tencentcloudkms'
          - './wrappers/transit'
        go: ["1.22"]
        platform: [ubuntu-latest] # can not run in macOS and Windows
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
        with:
          go-version: ${{ matrix.go }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: go mod package cache
        uses: actions/cache@2f8e54208210a422b2efd51efaa6bd6d7ca8920f # v3.4.3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ matrix.go }}-${{ hashFiles('tests/go.mod') }}

      - name: Tests
        working-directory: ${{ matrix.directory }}
        run: go test ./...

      - name: Container tests
        run: |-
          if [ -e "${{ matrix.directory }}/Dockerfile" ]; then
            docker build -f "${{ matrix.directory }}/Dockerfile" .
          fi
